### ISSUE TITLE
MVR checklist

### ISSUE THREAD

**Issue by eigenhombre** [eigenhombre/tableworld#1]
From https://gist.github.com/eigenhombre/204400c786f9dba3a8d3193d3ce1542a:

See also: http://johnj.com/posts/practices/

- [x] LICENSE file, including disclaimer
- [x] Automated build via Docker and GitHub Actions
- [x] Automated builds include unit tests
- [x] Automated builds include linting
- [x] Artwork
- [x] Versioned
- [x] Link to API and/or `help` output
- [x] Release procedure is automated
- [x] Project available in public package manager
- [x] Track outstanding TODOs in Issues
- [x] Project has a README, with
  - [x] Minimum snippet / example; ideally, auto-updated in README.
  - [x] Build badge
  - [x] How to check out and build the software locally
  - [x] How to deploy, or directions to deploy documentation
  - [x] Where to find logs, or directions to run book
  - [x] How alerts, if any, are configured
  - [x] What, if anything, should be done if ownership changes (individual, or team)
  - [x] Links to any auto-generated code documentation
  - [x] Backup procedure is documented
  - [x] Anything that is incorrect or outdated should be removed.
